name: Run every 1 hour

on:
  schedule:
    - cron: "20 * * * *"

jobs:
  cron:
    name: Run every 1 hour
    runs-on: ubuntu-latest

    steps:
      - name: Hello World
        run: echo "Hello World"
        